<?php return array (
  'sans-serif' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold' => $rootDir . '/lib/fonts/ZapfDingbats',
    'italic' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold_italic' => $rootDir . '/lib/fonts/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $rootDir . '/lib/fonts/Symbol',
    'bold' => $rootDir . '/lib/fonts/Symbol',
    'italic' => $rootDir . '/lib/fonts/Symbol',
    'bold_italic' => $rootDir . '/lib/fonts/Symbol',
  ),
  'serif' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSans-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSans-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSans-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSansMono-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSansMono-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSansMono-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSerif-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSerif-BoldItalic',
    'italic' => $rootDir . '/lib/fonts/DejaVuSerif-Italic',
    'normal' => $rootDir . '/lib/fonts/DejaVuSerif',
  ),
  'glyphicons halflings' => array(
    'normal' => $fontDir . '/glyphicons-halflings-normal_a10af4baeca73ce84ea24f3c18ee7213',
  ),
  'fontawesome' => array(
    'normal' => $fontDir . '/fontawesome-normal_218c84163998706ffedda6dc4d4439ce',
  ),
  'roboto' => array(
    '100_italic' => $fontDir . '/roboto-100-italic_f11cf67fa184ec5467ecdf37c629d86f',
    '300_italic' => $fontDir . '/roboto-300-italic_60fd1c5c48964f53c185886d78f6dd92',
    'italic' => $fontDir . '/roboto-italic_d5c10dd70a66238a4d11751aca1ac2f6',
    '500_italic' => $fontDir . '/roboto-500-italic_cb3389574fec6f0962ed3b8e8df3657a',
    'bold_italic' => $fontDir . '/roboto-bold-italic_3c4c982d93d98be963531fd17b72c633',
    '900_italic' => $fontDir . '/roboto-900-italic_88fdfb383ea3335a2ea849c31af79315',
    '100' => $fontDir . '/roboto-100_d876775dd3daf87873e6dd250e9c4c9e',
    '300' => $fontDir . '/roboto-300_21960201651f2ea862182ff34dfd5ead',
    'normal' => $fontDir . '/roboto-normal_9fa47a070a8b30b595086d70bb7ac78c',
    '500' => $fontDir . '/roboto-500_d0dcda9e813eb9b854a1cc044831f6fe',
    'bold' => $fontDir . '/roboto-bold_3d0ad20d45ace845335f9e6c390a09d9',
    '900' => $fontDir . '/roboto-900_509a5e5b153550862359e315131088d5',
  ),
  'roboto condensed' => array(
    '300_italic' => $fontDir . '/roboto-condensed-300-italic_54f52fd851539e7efb6dab8385e5a0f6',
    'italic' => $fontDir . '/roboto-condensed-italic_56097a73c00d191e4d2856a9a019d7a0',
    'bold_italic' => $fontDir . '/roboto-condensed-bold-italic_368648c4b06ca372e379753bb2fecdc9',
    '300' => $fontDir . '/roboto-condensed-300_7936413cf1b2d5ce5ae063d636ddc719',
    'normal' => $fontDir . '/roboto-condensed-normal_b1c81c5b8bff9fc82e79f049bb7c20e9',
    'bold' => $fontDir . '/roboto-condensed-bold_b62ecde992a70434b192f443feff6b62',
  ),
) ?>